### ISSUE TITLE
Unable to install cfdev Plugin

### ISSUE THREAD

**Issue by erpost** [cloudfoundry/cli-plugin-repo#407]
Hello, when attempting to run the following command-

`cf install-plugin cfdev`

the following error pops-

$ cf install-plugin cfdev
Searching CF-Community for plugin cfdev...
Plugin cfdev 0.0.18 found in: CF-Community
Attention: Plugins are binaries written by potentially untrusted authors.
Install and use plugins at your own risk.
Do you want to install the plugin cfdev? [yN]: y
Starting download of plugin binary from repository CF-Community...
Get "https://d3p1cc0zb2wjno.cloudfront.net/cfdev/cfdev-v0.0.18-rc.36-darwin": dial tcp: lookup d3p1cc0zb2wjno.cloudfront.net: no such host
FAILED

**Comment by davidmehi** [comment]
I experienced the same error as well.  The url is specified at https://github.com/cloudfoundry/cli-plugin-repo/blob/master/repo-index.yml#L525

Looks like the url is no longer valid.

**Comment by norman-abramovitz** [comment]
I am finding all the linux based plugins that I tried do not install.

	Stack Trace
			goroutine 1 [running]:
	code.cloudfoundry.org/cli/util/panichandler.HandlePanic()
		/tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/util/panichandler/handler.go:19 +0x85
	panic(0xfb6f00, 0x125f7a0)
		/usr/local/go/src/runtime/panic.go:965 +0x1b9
	code.cloudfoundry.org/cli/util/configv3.(*Config).AddPlugin(0xc000334300, 0xc000346280, 0xc, 0xc0003ea8e0, 0x1e, 0x1, 0x0, 0x3, 0x0, 0x0, ...)
		/tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/util/configv3/plugins_config.go:91 +0x56
	code.cloudfoundry.org/cli/actor/pluginaction.Actor.InstallPluginFromPath(0x7fb7b6d0f1a8, 0xc000334300, 0x1280b08, 0xc00004a0c0, 0xc000396300, 0x29, 0xc000346280, 0xc, 0xc0003ea8e0, 0x1e, ...)
		/tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/actor/pluginaction/install.go:181 +0x1b5
	code.cloudfoundry.org/cli/command/common.InstallPluginCommand.installPlugin(0x7ffe40a5f91e, 0xc, 0x100, 0x7ffe40a5f911, 0xc, 0x0, 0x0, 0x0, 0x0, 0x129b438, ...)
